# Generated by Django 2.2.7 on 2021-03-31 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_order_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
