# Generated by Django 3.1.7 on 2021-04-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0006_auto_20210403_0201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
