# Generated by Django 3.1.7 on 2021-04-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0010_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
